deploy:
  script:
    - cp $DEPLOY_KEY deploy && chmod 400 deploy
    - git remote add github git@github.com:fruition/mac-dev-shim.git || true
    - GIT_SSH_COMMAND="ssh -i deploy -o UserKnownHostsFile=$KNOWN_HOSTS"
      git push github HEAD:$CI_COMMIT_REF_NAME
